#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)" 
if ! head -1 "$1" | grep -qE "^(specie)-[[:digit:]]+: "; then 
echo "Bad commit message, see example: specie-123: commit message" 
echo "-" 
echo "Your commit message was:" 
echo $message 
echo "-" 
exit 1 
fi